.PHONY: clean All

All:
	@echo "----------Building project:[ Q12 - Debug ]----------"
	@cd "/Users/dovetales/Desktop/Griffith/1806ICT_Prog_Fund/code/1806ICTWorkshops/examPractice/Q12" && "$(MAKE)" -f  "Q12.mk"
clean:
	@echo "----------Cleaning project:[ Q12 - Debug ]----------"
	@cd "/Users/dovetales/Desktop/Griffith/1806ICT_Prog_Fund/code/1806ICTWorkshops/examPractice/Q12" && "$(MAKE)" -f  "Q12.mk" clean
