.PHONY: clean All

All:
	@echo "----------Building project:[ array1 - Debug ]----------"
	@cd "array1" && "$(MAKE)" -f  "array1.mk"
clean:
	@echo "----------Cleaning project:[ array1 - Debug ]----------"
	@cd "array1" && "$(MAKE)" -f  "array1.mk" clean
