.PHONY: clean All

All:
	@echo "----------Building project:[ countChars - Debug ]----------"
	@cd "countChars" && "$(MAKE)" -f  "countChars.mk"
clean:
	@echo "----------Cleaning project:[ countChars - Debug ]----------"
	@cd "countChars" && "$(MAKE)" -f  "countChars.mk" clean
