.PHONY: clean All

All:
	@echo "----------Building project:[ upperLower - Debug ]----------"
	@cd "upperLower" && "$(MAKE)" -f  "upperLower.mk"
clean:
	@echo "----------Cleaning project:[ upperLower - Debug ]----------"
	@cd "upperLower" && "$(MAKE)" -f  "upperLower.mk" clean
