.PHONY: clean All

All:
	@echo "----------Building project:[ fgetsInput - Debug ]----------"
	@cd "fgetsInput" && "$(MAKE)" -f  "fgetsInput.mk"
clean:
	@echo "----------Cleaning project:[ fgetsInput - Debug ]----------"
	@cd "fgetsInput" && "$(MAKE)" -f  "fgetsInput.mk" clean
