.PHONY: clean All

All:
	@echo "----------Building project:[ removeString - Debug ]----------"
	@cd "removeString" && "$(MAKE)" -f  "removeString.mk"
clean:
	@echo "----------Cleaning project:[ removeString - Debug ]----------"
	@cd "removeString" && "$(MAKE)" -f  "removeString.mk" clean
