.PHONY: clean All

All:
	@echo "----------Building project:[ compGuess - Debug ]----------"
	@cd "compGuess" && "$(MAKE)" -f  "compGuess.mk"
clean:
	@echo "----------Cleaning project:[ compGuess - Debug ]----------"
	@cd "compGuess" && "$(MAKE)" -f  "compGuess.mk" clean
