.PHONY: clean All

All:
	@echo "----------Building project:[ Q2_leastCommonMultiple - Debug ]----------"
	@cd "Q2_leastCommonMultiple" && "$(MAKE)" -f  "Q2_leastCommonMultiple.mk"
clean:
	@echo "----------Cleaning project:[ Q2_leastCommonMultiple - Debug ]----------"
	@cd "Q2_leastCommonMultiple" && "$(MAKE)" -f  "Q2_leastCommonMultiple.mk" clean
