.PHONY: clean All

All:
	@echo "----------Building project:[ Q3_primeNumber - Debug ]----------"
	@cd "Q3_primeNumber" && "$(MAKE)" -f  "Q3_primeNumber.mk"
clean:
	@echo "----------Cleaning project:[ Q3_primeNumber - Debug ]----------"
	@cd "Q3_primeNumber" && "$(MAKE)" -f  "Q3_primeNumber.mk" clean
