.PHONY: clean All

All:
	@echo "----------Building project:[ floritsStruct - Debug ]----------"
	@cd "floritsStruct" && "$(MAKE)" -f  "floritsStruct.mk"
clean:
	@echo "----------Cleaning project:[ floritsStruct - Debug ]----------"
	@cd "floritsStruct" && "$(MAKE)" -f  "floritsStruct.mk" clean
