.PHONY: clean All

All:
	@echo "----------Building project:[ studentStruct - Debug ]----------"
	@cd "studentStruct" && "$(MAKE)" -f  "studentStruct.mk"
clean:
	@echo "----------Cleaning project:[ studentStruct - Debug ]----------"
	@cd "studentStruct" && "$(MAKE)" -f  "studentStruct.mk" clean
