.PHONY: clean All

All:
	@echo "----------Building project:[ wk5DynMemAllocation - Debug ]----------"
	@cd "wk5DynMemAllocation" && "$(MAKE)" -f  "wk5DynMemAllocation.mk"
clean:
	@echo "----------Cleaning project:[ wk5DynMemAllocation - Debug ]----------"
	@cd "wk5DynMemAllocation" && "$(MAKE)" -f  "wk5DynMemAllocation.mk" clean
