.PHONY: clean All

All:
	@echo "----------Building project:[ Q6_clumps - Debug ]----------"
	@cd "Q6_clumps" && "$(MAKE)" -f  "Q6_clumps.mk"
clean:
	@echo "----------Cleaning project:[ Q6_clumps - Debug ]----------"
	@cd "Q6_clumps" && "$(MAKE)" -f  "Q6_clumps.mk" clean
