.PHONY: clean All

All:
	@echo "----------Building project:[ wk5Pointers - Debug ]----------"
	@cd "wk5Pointers" && "$(MAKE)" -f  "wk5Pointers.mk"
clean:
	@echo "----------Cleaning project:[ wk5Pointers - Debug ]----------"
	@cd "wk5Pointers" && "$(MAKE)" -f  "wk5Pointers.mk" clean
