.PHONY: clean All

All:
	@echo "----------Building project:[ Q3_changeit - Debug ]----------"
	@cd "/Users/dhruvdev/Desktop/1806_Programming_Fundementals/1806ICTWorkshops-master/1806ICTWorkshops/workshop6Pointers/Q3_changeit" && "$(MAKE)" -f  "Q3_changeit.mk"
clean:
	@echo "----------Cleaning project:[ Q3_changeit - Debug ]----------"
	@cd "/Users/dhruvdev/Desktop/1806_Programming_Fundementals/1806ICTWorkshops-master/1806ICTWorkshops/workshop6Pointers/Q3_changeit" && "$(MAKE)" -f  "Q3_changeit.mk" clean
