.PHONY: clean All

All:
	@echo "----------Building project:[ Q2 - Debug ]----------"
	@cd "Q2" && "$(MAKE)" -f  "Q2.mk"
clean:
	@echo "----------Cleaning project:[ Q2 - Debug ]----------"
	@cd "Q2" && "$(MAKE)" -f  "Q2.mk" clean
