.PHONY: clean All

All:
	@echo "----------Building project:[ Q1_examples - Debug ]----------"
	@cd "Q1_examples" && "$(MAKE)" -f  "Q1_examples.mk"
clean:
	@echo "----------Cleaning project:[ Q1_examples - Debug ]----------"
	@cd "Q1_examples" && "$(MAKE)" -f  "Q1_examples.mk" clean
