.PHONY: clean All

All:
	@echo "----------Building project:[ StringsLectureExamples - Debug ]----------"
	@cd "StringsLectureExamples" && "$(MAKE)" -f  "StringsLectureExamples.mk"
clean:
	@echo "----------Cleaning project:[ StringsLectureExamples - Debug ]----------"
	@cd "StringsLectureExamples" && "$(MAKE)" -f  "StringsLectureExamples.mk" clean
