.PHONY: clean All

All:
	@echo "----------Building project:[ allocatingMemory - Debug ]----------"
	@cd "allocatingMemory" && "$(MAKE)" -f  "allocatingMemory.mk"
clean:
	@echo "----------Cleaning project:[ allocatingMemory - Debug ]----------"
	@cd "allocatingMemory" && "$(MAKE)" -f  "allocatingMemory.mk" clean
