.PHONY: clean All

All:
	@echo "----------Building project:[ replaceChar - Debug ]----------"
	@cd "replaceChar" && "$(MAKE)" -f  "replaceChar.mk"
clean:
	@echo "----------Cleaning project:[ replaceChar - Debug ]----------"
	@cd "replaceChar" && "$(MAKE)" -f  "replaceChar.mk" clean
