.PHONY: clean All

All:
	@echo "----------Building project:[ Q4_monthlyPayment - Debug ]----------"
	@cd "Q4_monthlyPayment" && "$(MAKE)" -f  "Q4_monthlyPayment.mk"
clean:
	@echo "----------Cleaning project:[ Q4_monthlyPayment - Debug ]----------"
	@cd "Q4_monthlyPayment" && "$(MAKE)" -f  "Q4_monthlyPayment.mk" clean
