.PHONY: clean All

All:
	@echo "----------Building project:[ power - Debug ]----------"
	@cd "power" && "$(MAKE)" -f  "power.mk"
clean:
	@echo "----------Cleaning project:[ power - Debug ]----------"
	@cd "power" && "$(MAKE)" -f  "power.mk" clean
