.PHONY: clean All

All:
	@echo "----------Building project:[ recursion - Debug ]----------"
	@cd "/Users/dovetales/Desktop/Griffith/1806ICT_Prog_Fund/code/1806ICTWorkshops/wk10Recursion/recursion" && "$(MAKE)" -f  "recursion.mk"
clean:
	@echo "----------Cleaning project:[ recursion - Debug ]----------"
	@cd "/Users/dovetales/Desktop/Griffith/1806ICT_Prog_Fund/code/1806ICTWorkshops/wk10Recursion/recursion" && "$(MAKE)" -f  "recursion.mk" clean
