.PHONY: clean All

All:
	@echo "----------Building project:[ Q12_solvePolynomial - Debug ]----------"
	@cd "Q12_solvePolynomial" && "$(MAKE)" -f  "Q12_solvePolynomial.mk"
clean:
	@echo "----------Cleaning project:[ Q12_solvePolynomial - Debug ]----------"
	@cd "Q12_solvePolynomial" && "$(MAKE)" -f  "Q12_solvePolynomial.mk" clean
