.PHONY: clean All

All:
	@echo "----------Building project:[ Q4_charNum - Debug ]----------"
	@cd "Q4_charNum" && "$(MAKE)" -f  "Q4_charNum.mk"
clean:
	@echo "----------Cleaning project:[ Q4_charNum - Debug ]----------"
	@cd "Q4_charNum" && "$(MAKE)" -f  "Q4_charNum.mk" clean
