.PHONY: clean All

All:
	@echo "----------Building project:[ Q1_usingCount - Debug ]----------"
	@cd "Q1_usingCount" && "$(MAKE)" -f  "Q1_usingCount.mk"
clean:
	@echo "----------Cleaning project:[ Q1_usingCount - Debug ]----------"
	@cd "Q1_usingCount" && "$(MAKE)" -f  "Q1_usingCount.mk" clean
