.PHONY: clean All

All:
	@echo "----------Building project:[ Q4_integerToEnglish - Debug ]----------"
	@cd "Q4_integerToEnglish" && "$(MAKE)" -f  "Q4_integerToEnglish.mk"
clean:
	@echo "----------Cleaning project:[ Q4_integerToEnglish - Debug ]----------"
	@cd "Q4_integerToEnglish" && "$(MAKE)" -f  "Q4_integerToEnglish.mk" clean
