.PHONY: clean All

All:
	@echo "----------Building project:[ Q8_printCascade - Debug ]----------"
	@cd "Q8_printCascade" && "$(MAKE)" -f  "Q8_printCascade.mk"
clean:
	@echo "----------Cleaning project:[ Q8_printCascade - Debug ]----------"
	@cd "Q8_printCascade" && "$(MAKE)" -f  "Q8_printCascade.mk" clean
