.PHONY: clean All

All:
	@echo "----------Building project:[ Q2_nFactorial - Debug ]----------"
	@cd "Q2_nFactorial" && "$(MAKE)" -f  "Q2_nFactorial.mk"
clean:
	@echo "----------Cleaning project:[ Q2_nFactorial - Debug ]----------"
	@cd "Q2_nFactorial" && "$(MAKE)" -f  "Q2_nFactorial.mk" clean
