.PHONY: clean All

All:
	@echo "----------Building project:[ numDays - Debug ]----------"
	@cd "numDays" && "$(MAKE)" -f  "numDays.mk"
clean:
	@echo "----------Cleaning project:[ numDays - Debug ]----------"
	@cd "numDays" && "$(MAKE)" -f  "numDays.mk" clean
