.PHONY: clean All

All:
	@echo "----------Building project:[ Q5_4after3 - Debug ]----------"
	@cd "Q5_4after3" && "$(MAKE)" -f  "Q5_4after3.mk"
clean:
	@echo "----------Cleaning project:[ Q5_4after3 - Debug ]----------"
	@cd "Q5_4after3" && "$(MAKE)" -f  "Q5_4after3.mk" clean
