.PHONY: clean All

All:
	@echo "----------Building project:[ Q3_evenFirst - Debug ]----------"
	@cd "Q3_evenFirst" && "$(MAKE)" -f  "Q3_evenFirst.mk"
clean:
	@echo "----------Cleaning project:[ Q3_evenFirst - Debug ]----------"
	@cd "Q3_evenFirst" && "$(MAKE)" -f  "Q3_evenFirst.mk" clean
