.PHONY: clean All

All:
	@echo "----------Building project:[ Q2_maxMinArray - Debug ]----------"
	@cd "Q2_maxMinArray" && "$(MAKE)" -f  "Q2_maxMinArray.mk"
clean:
	@echo "----------Cleaning project:[ Q2_maxMinArray - Debug ]----------"
	@cd "Q2_maxMinArray" && "$(MAKE)" -f  "Q2_maxMinArray.mk" clean
