.PHONY: clean All

All:
	@echo "----------Building project:[ greatestCommonDivisor - Debug ]----------"
	@cd "greatestCommonDenominator" && "$(MAKE)" -f  "greatestCommonDivisor.mk"
clean:
	@echo "----------Cleaning project:[ greatestCommonDivisor - Debug ]----------"
	@cd "greatestCommonDenominator" && "$(MAKE)" -f  "greatestCommonDivisor.mk" clean
