.PHONY: clean All

All:
	@echo "----------Building project:[ lectureEgs - Debug ]----------"
	@cd "lectureEgs" && "$(MAKE)" -f  "lectureEgs.mk"
clean:
	@echo "----------Cleaning project:[ lectureEgs - Debug ]----------"
	@cd "lectureEgs" && "$(MAKE)" -f  "lectureEgs.mk" clean
