.PHONY: clean All

All:
	@echo "----------Building project:[ program1 - Debug ]----------"
	@cd "program1" && "$(MAKE)" -f  "program1.mk"
clean:
	@echo "----------Cleaning project:[ program1 - Debug ]----------"
	@cd "program1" && "$(MAKE)" -f  "program1.mk" clean
