.PHONY: clean All

All:
	@echo "----------Building project:[ newProject - Debug ]----------"
	@cd "newProject" && "$(MAKE)" -f  "newProject.mk"
clean:
	@echo "----------Cleaning project:[ newProject - Debug ]----------"
	@cd "newProject" && "$(MAKE)" -f  "newProject.mk" clean
