.PHONY: clean All

All:
	@echo "----------Building project:[ workshop2 - Debug ]----------"
	@cd "workshop2" && "$(MAKE)" -f  "workshop2.mk"
clean:
	@echo "----------Cleaning project:[ workshop2 - Debug ]----------"
	@cd "workshop2" && "$(MAKE)" -f  "workshop2.mk" clean
